-- Animalin multi-tenant SaaS schema (shared database, shared schema, tenant_id isolation)

CREATE TABLE plans (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(40)   NOT NULL UNIQUE,
    name_es             VARCHAR(120)  NOT NULL,
    name_en             VARCHAR(120)  NOT NULL,
    description_es      VARCHAR(500),
    description_en      VARCHAR(500),
    max_users           INT           NOT NULL DEFAULT 5,
    max_veterinarians   INT           NOT NULL DEFAULT 2,
    max_branches        INT           NOT NULL DEFAULT 1,
    max_storage_mb      INT           NOT NULL DEFAULT 1024,
    max_messages_month  INT           NOT NULL DEFAULT 200,
    reports_enabled     BOOLEAN       NOT NULL DEFAULT TRUE,
    messaging_enabled   BOOLEAN       NOT NULL DEFAULT TRUE,
    laboratory_enabled  BOOLEAN       NOT NULL DEFAULT FALSE,
    monthly_price       NUMERIC(10, 2) NOT NULL DEFAULT 0,
    active              BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tenants (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                VARCHAR(80)   NOT NULL UNIQUE,
    name                VARCHAR(180)  NOT NULL,
    commercial_name     VARCHAR(180),
    logo_url            VARCHAR(500),
    dark_logo_url       VARCHAR(500),
    icon_url            VARCHAR(500),
    email               VARCHAR(180),
    phone               VARCHAR(40),
    address             VARCHAR(240),
    city                VARCHAR(120),
    country             VARCHAR(120),
    website             VARCHAR(240),
    instagram           VARCHAR(240),
    facebook            VARCHAR(240),
    timezone            VARCHAR(64)   NOT NULL DEFAULT 'Europe/Madrid',
    currency            VARCHAR(8)    NOT NULL DEFAULT 'EUR',
    default_locale      VARCHAR(8)    NOT NULL DEFAULT 'es',
    status              VARCHAR(20)   NOT NULL DEFAULT 'TRIAL',
    plan_id             BIGINT        REFERENCES plans (id),
    trial_ends_at       TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by          VARCHAR(120),
    updated_by          VARCHAR(120),
    deleted             BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP
);

CREATE INDEX idx_tenants_status ON tenants (status);
CREATE INDEX idx_tenants_plan ON tenants (plan_id);

CREATE TABLE subscriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL REFERENCES tenants (id),
    plan_id             BIGINT        NOT NULL REFERENCES plans (id),
    status              VARCHAR(20)   NOT NULL DEFAULT 'TRIAL',
    trial               BOOLEAN       NOT NULL DEFAULT TRUE,
    started_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_period_end  TIMESTAMP,
    cancelled_at        TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP
);

CREATE INDEX idx_subscriptions_tenant ON subscriptions (tenant_id, status);

CREATE TABLE tenant_settings (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT       NOT NULL UNIQUE REFERENCES tenants (id),
    date_format                 VARCHAR(32)  NOT NULL DEFAULT 'dd/MM/yyyy',
    default_appointment_min     INT          NOT NULL DEFAULT 30,
    cancellation_hours          INT          NOT NULL DEFAULT 12,
    notify_email                BOOLEAN      NOT NULL DEFAULT TRUE,
    notify_push                 BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled_locales             VARCHAR(32)  NOT NULL DEFAULT 'es,en',
    updated_at                  TIMESTAMP,
    updated_by                  VARCHAR(120)
);

CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    name_es         VARCHAR(120) NOT NULL,
    name_en         VARCHAR(120) NOT NULL,
    description_es  VARCHAR(500),
    description_en  VARCHAR(500),
    system_role     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80)  NOT NULL UNIQUE,
    name_es     VARCHAR(160) NOT NULL,
    name_en     VARCHAR(160) NOT NULL,
    module      VARCHAR(80)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles (id),
    permission_id BIGINT NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(180) NOT NULL UNIQUE,
    password_hash   VARCHAR(120) NOT NULL,
    first_name      VARCHAR(80)  NOT NULL,
    last_name       VARCHAR(120) NOT NULL,
    phone           VARCHAR(40),
    document_id     VARCHAR(40),
    avatar_url      VARCHAR(500),
    locale          VARCHAR(8)   NOT NULL DEFAULT 'es',
    theme           VARCHAR(16)  NOT NULL DEFAULT 'system',
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE tenant_memberships (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenants (id),
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    role_id     BIGINT      NOT NULL REFERENCES roles (id),
    branch_id   BIGINT,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, user_id)
);

CREATE INDEX idx_memberships_user ON tenant_memberships (user_id);
CREATE INDEX idx_memberships_tenant ON tenant_memberships (tenant_id, status);

CREATE TABLE refresh_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users (id),
    tenant_id     BIGINT       REFERENCES tenants (id),
    token_hash    VARCHAR(128) NOT NULL UNIQUE,
    expires_at    TIMESTAMP    NOT NULL,
    revoked       BOOLEAN      NOT NULL DEFAULT FALSE,
    replaced_by   VARCHAR(128),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token_hash  VARCHAR(128) NOT NULL UNIQUE,
    expires_at  TIMESTAMP    NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token_hash  VARCHAR(128) NOT NULL UNIQUE,
    expires_at  TIMESTAMP    NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE branches (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tenants (id),
    name        VARCHAR(160) NOT NULL,
    address     VARCHAR(240),
    city        VARCHAR(120),
    country     VARCHAR(120),
    phone       VARCHAR(40),
    email       VARCHAR(180),
    timezone    VARCHAR(64)  NOT NULL DEFAULT 'Europe/Madrid',
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    created_by  VARCHAR(120),
    updated_by  VARCHAR(120),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP
);

CREATE INDEX idx_branches_tenant ON branches (tenant_id, active);

CREATE TABLE branch_hours (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenants (id),
    branch_id   BIGINT      NOT NULL REFERENCES branches (id),
    day_of_week INT         NOT NULL,
    open_time   TIME        NOT NULL,
    close_time  TIME        NOT NULL,
    closed      BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE veterinarians (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenants (id),
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    branch_id       BIGINT       REFERENCES branches (id),
    specialty       VARCHAR(160),
    license_number  VARCHAR(80),
    bio             VARCHAR(2000),
    photo_url       VARCHAR(500),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP,
    UNIQUE (tenant_id, user_id)
);

CREATE INDEX idx_vets_tenant ON veterinarians (tenant_id, status);

CREATE TABLE veterinarian_schedules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL REFERENCES tenants (id),
    veterinarian_id  BIGINT NOT NULL REFERENCES veterinarians (id),
    day_of_week      INT    NOT NULL,
    start_time       TIME   NOT NULL,
    end_time         TIME   NOT NULL,
    break_start      TIME,
    break_end        TIME
);

CREATE TABLE veterinarian_time_off (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    veterinarian_id  BIGINT       NOT NULL REFERENCES veterinarians (id),
    start_at         TIMESTAMP    NOT NULL,
    end_at           TIMESTAMP    NOT NULL,
    reason           VARCHAR(240),
    type             VARCHAR(40)  NOT NULL DEFAULT 'VACATION'
);

CREATE TABLE schedule_blocks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    branch_id        BIGINT       REFERENCES branches (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    start_at         TIMESTAMP    NOT NULL,
    end_at           TIMESTAMP    NOT NULL,
    reason           VARCHAR(240),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenants (id),
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    branch_id   BIGINT      REFERENCES branches (id),
    position    VARCHAR(120),
    hire_date   DATE,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    created_by  VARCHAR(120),
    updated_by  VARCHAR(120),
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP,
    UNIQUE (tenant_id, user_id)
);

CREATE TABLE owners (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tenants (id),
    user_id     BIGINT       REFERENCES users (id),
    first_name  VARCHAR(80)  NOT NULL,
    last_name   VARCHAR(120) NOT NULL,
    document_id VARCHAR(40),
    phone       VARCHAR(40),
    email       VARCHAR(180),
    address     VARCHAR(240),
    city        VARCHAR(120),
    country     VARCHAR(120),
    notes       VARCHAR(2000),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    created_by  VARCHAR(120),
    updated_by  VARCHAR(120),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP
);

CREATE INDEX idx_owners_tenant_status ON owners (tenant_id, status);
CREATE INDEX idx_owners_tenant_email ON owners (tenant_id, email);
CREATE INDEX idx_owners_user ON owners (user_id);

CREATE TABLE pets (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT       NOT NULL REFERENCES tenants (id),
    owner_id                BIGINT       NOT NULL REFERENCES owners (id),
    branch_id               BIGINT       REFERENCES branches (id),
    primary_veterinarian_id BIGINT       REFERENCES veterinarians (id),
    internal_code           VARCHAR(40),
    name                    VARCHAR(120) NOT NULL,
    species                 VARCHAR(40)  NOT NULL,
    breed                   VARCHAR(120),
    sex                     VARCHAR(20),
    birth_date              DATE,
    weight_kg               NUMERIC(8, 2),
    color                   VARCHAR(80),
    microchip               VARCHAR(64),
    reproductive_status     VARCHAR(40),
    sterilized              BOOLEAN      NOT NULL DEFAULT FALSE,
    allergies               VARCHAR(1000),
    medical_conditions      VARCHAR(1000),
    notes                   VARCHAR(2000),
    photo_url               VARCHAR(500),
    status                  VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP,
    created_by              VARCHAR(120),
    updated_by              VARCHAR(120),
    deleted                 BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMP,
    UNIQUE (tenant_id, internal_code)
);

CREATE INDEX idx_pets_tenant_owner ON pets (tenant_id, owner_id);
CREATE INDEX idx_pets_tenant_status ON pets (tenant_id, status);
CREATE INDEX idx_pets_microchip ON pets (tenant_id, microchip);
CREATE INDEX idx_pets_vet ON pets (tenant_id, primary_veterinarian_id);

CREATE TABLE pet_weight_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT        NOT NULL REFERENCES tenants (id),
    pet_id      BIGINT        NOT NULL REFERENCES pets (id),
    recorded_at TIMESTAMP     NOT NULL,
    weight_kg   NUMERIC(8, 2) NOT NULL,
    notes       VARCHAR(240)
);

CREATE TABLE clinic_services (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT        NOT NULL REFERENCES tenants (id),
    name_es        VARCHAR(160)  NOT NULL,
    name_en        VARCHAR(160)  NOT NULL,
    description_es VARCHAR(500),
    description_en VARCHAR(500),
    duration_min   INT           NOT NULL DEFAULT 30,
    price          NUMERIC(10, 2) NOT NULL DEFAULT 0,
    category       VARCHAR(80),
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(120),
    updated_by     VARCHAR(120),
    deleted        BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMP
);

CREATE INDEX idx_services_tenant ON clinic_services (tenant_id, active);

CREATE TABLE appointments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    owner_id         BIGINT       NOT NULL REFERENCES owners (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    service_id       BIGINT       REFERENCES clinic_services (id),
    branch_id        BIGINT       REFERENCES branches (id),
    start_at         TIMESTAMP    NOT NULL,
    end_at           TIMESTAMP    NOT NULL,
    duration_min     INT          NOT NULL,
    reason           VARCHAR(500),
    notes            VARCHAR(2000),
    status           VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(120),
    updated_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_appointments_tenant_date ON appointments (tenant_id, start_at);
CREATE INDEX idx_appointments_tenant_status ON appointments (tenant_id, status);
CREATE INDEX idx_appointments_vet ON appointments (tenant_id, veterinarian_id, start_at);
CREATE INDEX idx_appointments_pet ON appointments (tenant_id, pet_id);
CREATE INDEX idx_appointments_owner ON appointments (tenant_id, owner_id);

CREATE TABLE consultations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id                 BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id        BIGINT       REFERENCES veterinarians (id),
    appointment_id         BIGINT       REFERENCES appointments (id),
    branch_id              BIGINT       REFERENCES branches (id),
    consulted_at           TIMESTAMP    NOT NULL,
    reason                 VARCHAR(500),
    symptoms               VARCHAR(2000),
    anamnesis              VARCHAR(4000),
    physical_exam          VARCHAR(4000),
    diagnosis              VARCHAR(2000),
    differential_diagnosis VARCHAR(2000),
    treatment_plan         VARCHAR(4000),
    recommendations        VARCHAR(4000),
    internal_notes         VARCHAR(4000),
    next_control_at        TIMESTAMP,
    status                 VARCHAR(30)  NOT NULL DEFAULT 'IN_PROGRESS',
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP,
    created_by             VARCHAR(120),
    updated_by             VARCHAR(120),
    deleted                BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at             TIMESTAMP
);

CREATE INDEX idx_consultations_tenant_pet ON consultations (tenant_id, pet_id);
CREATE INDEX idx_consultations_vet ON consultations (tenant_id, veterinarian_id);

CREATE TABLE diagnoses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    consultation_id  BIGINT       NOT NULL REFERENCES consultations (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    code             VARCHAR(40),
    name             VARCHAR(240) NOT NULL,
    differential     BOOLEAN      NOT NULL DEFAULT FALSE,
    notes            VARCHAR(1000),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE TABLE vital_signs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT    NOT NULL REFERENCES tenants (id),
    consultation_id       BIGINT    REFERENCES consultations (id),
    pet_id                BIGINT    NOT NULL REFERENCES pets (id),
    recorded_at           TIMESTAMP NOT NULL,
    temperature_c         NUMERIC(5, 2),
    weight_kg             NUMERIC(8, 2),
    heart_rate            INT,
    respiratory_rate      INT,
    blood_pressure        VARCHAR(20),
    mucous_color          VARCHAR(40),
    capillary_refill      VARCHAR(20),
    notes                 VARCHAR(500),
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            VARCHAR(120),
    deleted               BOOLEAN   NOT NULL DEFAULT FALSE,
    deleted_at            TIMESTAMP
);

CREATE TABLE medications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    name             VARCHAR(180) NOT NULL,
    active_principle VARCHAR(180),
    presentation     VARCHAR(120),
    species          VARCHAR(80),
    notes            VARCHAR(500),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE TABLE treatments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    consultation_id  BIGINT       REFERENCES consultations (id),
    name             VARCHAR(180) NOT NULL,
    description      VARCHAR(2000),
    start_date       DATE         NOT NULL,
    end_date         DATE,
    status           VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    notes            VARCHAR(2000),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(120),
    updated_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_treatments_tenant_pet ON treatments (tenant_id, pet_id);
CREATE INDEX idx_treatments_status ON treatments (tenant_id, status);

CREATE TABLE treatment_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id    BIGINT       NOT NULL REFERENCES treatments (id),
    medication_id   BIGINT       REFERENCES medications (id),
    medication_name VARCHAR(180),
    dose            VARCHAR(80),
    frequency       VARCHAR(80),
    route           VARCHAR(80)
);

CREATE TABLE prescriptions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT    NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT    NOT NULL REFERENCES pets (id),
    owner_id         BIGINT    NOT NULL REFERENCES owners (id),
    veterinarian_id  BIGINT    REFERENCES veterinarians (id),
    consultation_id  BIGINT    REFERENCES consultations (id),
    issued_at        TIMESTAMP NOT NULL,
    notes            VARCHAR(2000),
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(120),
    updated_by       VARCHAR(120),
    deleted          BOOLEAN   NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_prescriptions_tenant_pet ON prescriptions (tenant_id, pet_id);

CREATE TABLE prescription_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id   BIGINT       NOT NULL REFERENCES prescriptions (id),
    medication_id     BIGINT       REFERENCES medications (id),
    medication_name   VARCHAR(180) NOT NULL,
    presentation      VARCHAR(120),
    dose              VARCHAR(80),
    frequency         VARCHAR(80),
    route             VARCHAR(80),
    duration          VARCHAR(80),
    notes             VARCHAR(500)
);

CREATE TABLE vaccine_catalog (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT       REFERENCES tenants (id),
    name_es               VARCHAR(160) NOT NULL,
    name_en               VARCHAR(160) NOT NULL,
    species               VARCHAR(40),
    default_interval_days INT,
    active                BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE vaccinations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    vaccine_id       BIGINT       REFERENCES vaccine_catalog (id),
    vaccine_name     VARCHAR(160) NOT NULL,
    brand            VARCHAR(120),
    lot              VARCHAR(80),
    applied_at       DATE         NOT NULL,
    next_dose_at     DATE,
    notes            VARCHAR(1000),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(120),
    updated_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_vaccinations_tenant_pet ON vaccinations (tenant_id, pet_id);
CREATE INDEX idx_vaccinations_next ON vaccinations (tenant_id, next_dose_at);

CREATE TABLE procedures (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    consultation_id  BIGINT       REFERENCES consultations (id),
    name             VARCHAR(180) NOT NULL,
    performed_at     TIMESTAMP    NOT NULL,
    notes            VARCHAR(2000),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE TABLE surgeries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    name             VARCHAR(180) NOT NULL,
    performed_at     TIMESTAMP    NOT NULL,
    anesthesia       VARCHAR(240),
    notes            VARCHAR(4000),
    outcome          VARCHAR(240),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE TABLE laboratory_results (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT       NOT NULL REFERENCES pets (id),
    veterinarian_id  BIGINT       REFERENCES veterinarians (id),
    consultation_id  BIGINT       REFERENCES consultations (id),
    name             VARCHAR(180) NOT NULL,
    lab_name         VARCHAR(160),
    collected_at     TIMESTAMP,
    result_summary   VARCHAR(4000),
    status           VARCHAR(30)  NOT NULL DEFAULT 'COMPLETED',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(120),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE TABLE stored_files (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       REFERENCES tenants (id),
    uploaded_by      BIGINT       REFERENCES users (id),
    file_name        VARCHAR(240) NOT NULL,
    content_type     VARCHAR(120),
    storage_key      VARCHAR(500) NOT NULL,
    size_bytes       BIGINT,
    category         VARCHAR(80),
    entity_type      VARCHAR(80),
    entity_id        BIGINT,
    public_file      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_files_tenant_entity ON stored_files (tenant_id, entity_type, entity_id);

CREATE TABLE documents (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    pet_id           BIGINT       REFERENCES pets (id),
    owner_id         BIGINT       REFERENCES owners (id),
    consultation_id  BIGINT       REFERENCES consultations (id),
    file_id          BIGINT       REFERENCES stored_files (id),
    uploaded_by      BIGINT       REFERENCES users (id),
    title            VARCHAR(240),
    category         VARCHAR(80),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_documents_tenant_pet ON documents (tenant_id, pet_id);

CREATE TABLE conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tenants (id),
    owner_id    BIGINT       REFERENCES owners (id),
    pet_id      BIGINT       REFERENCES pets (id),
    subject     VARCHAR(240),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE INDEX idx_conversations_tenant ON conversations (tenant_id, updated_at);

CREATE TABLE conversation_participants (
    conversation_id BIGINT NOT NULL REFERENCES conversations (id),
    user_id         BIGINT NOT NULL REFERENCES users (id),
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES tenants (id),
    conversation_id  BIGINT       NOT NULL REFERENCES conversations (id),
    sender_id        BIGINT       NOT NULL REFERENCES users (id),
    body             VARCHAR(4000),
    pet_id           BIGINT       REFERENCES pets (id),
    consultation_id  BIGINT       REFERENCES consultations (id),
    read_at          TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);

CREATE TABLE message_attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id   BIGINT       NOT NULL REFERENCES messages (id),
    file_id      BIGINT       REFERENCES stored_files (id),
    file_name    VARCHAR(240) NOT NULL,
    content_type VARCHAR(120),
    storage_key  VARCHAR(500) NOT NULL
);

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       REFERENCES tenants (id),
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    type        VARCHAR(60)  NOT NULL,
    title_es    VARCHAR(180) NOT NULL,
    title_en    VARCHAR(180) NOT NULL,
    body_es     VARCHAR(500),
    body_en     VARCHAR(500),
    entity_type VARCHAR(80),
    entity_id   BIGINT,
    read_at     TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notifications_user ON notifications (user_id, created_at);
CREATE INDEX idx_notifications_tenant ON notifications (tenant_id, created_at);

CREATE TABLE push_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token       VARCHAR(512) NOT NULL,
    platform    VARCHAR(40),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, token)
);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT,
    user_id      BIGINT,
    username     VARCHAR(180),
    action       VARCHAR(80)  NOT NULL,
    entity_type  VARCHAR(80)  NOT NULL,
    entity_id    BIGINT,
    details      VARCHAR(2000),
    old_value    VARCHAR(2000),
    new_value    VARCHAR(2000),
    ip_address   VARCHAR(64),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_tenant ON audit_logs (tenant_id, created_at);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);

CREATE TABLE platform_settings (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_email           VARCHAR(180) NOT NULL DEFAULT 'soporte@animalin.app',
    default_locale          VARCHAR(8)   NOT NULL DEFAULT 'es',
    default_trial_days      INT          NOT NULL DEFAULT 14,
    maintenance_mode        BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at              TIMESTAMP,
    updated_by              VARCHAR(120)
);
